# Default values for flask-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 3
maxReplicas: 10
minReplicas: 4
user: root
database: alf
image:
  repository: ibbuu/alf
  tag: latest
  pullPolicy: Always
service:
  name: alf
  externalPort: 80
  internalPort: 5000
ingress:
  enabled: true
  hosts:
    - alf-webapp.local
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
resources: {}
